name: Setup CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: readme
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: graphs
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/status-page/__sapper__/export/
          user_name: exportcomments-bot
          user_email: support@exportcomments.com
